In [1]:
import numpy as np

In [2]:
first_numpy_array = np.array([1,2,3,4])

In [3]:
print(first_numpy_array)

[1 2 3 4]


In [4]:
array_with_zeros = np.zeros((3,3))
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
array_with_ones = np.ones((3,3))
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
array_with_empty = np.empty((2,3))
print(array_with_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
np_linspace = np.linspace(1,6,10)
np_linspace

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [18]:
oneDArray = np.arange(15)
oneDArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
twoDArray = oneDArray.reshape(3,5)
print(twoDArray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
oneDArray = np.arange(45)
threeDArray = oneDArray.reshape(3,3,5)
print(threeDArray)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [22]:
np_linspace = np.linspace(4,13,7)
np_linspace

array([ 4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. ])

In [23]:
len(np_linspace)

7

In [28]:
np_city = np.array(['Ujire','Mysore','Singapore'])
print(np_city)

['Ujire' 'Mysore' 'Singapore']


In [29]:
np_city2 = np.array([['Ujire','Mysore','Singapore'],['Ujire1','Mysore1','Singapore1']])
print(np_city2)

[['Ujire' 'Mysore' 'Singapore']
 ['Ujire1' 'Mysore1' 'Singapore1']]


In [30]:
np_city.shape

(3,)

In [31]:
np_city2.shape

(2, 3)

In [32]:
np_city.size

3

In [33]:
np_city2.size

6

In [42]:
import numpy as np
first_trial_Cyclist = [1,2,3,4]
second_trial_Cyclist = [10,20,30,40]
npfirst = np.array(first_trial_Cyclist)
npsecond = np.array(second_trial_Cyclist)
print(npfirst)
print(npsecond)
print(npfirst.sum())

[1 2 3 4]
[10 20 30 40]
10


In [35]:
np.add(100,300)


400

In [37]:
np.multiply(10,30)

300

In [39]:
np.subtract(40,20)

20

In [40]:
np.divide(40,2)

20.0

In [41]:
nhrs = [5,6,8,10,7]
np_nhrs = np.array(nhrs)
rate_hr = 15 
Eachday_wage = np_nhrs*15
print(Eachday_wage)

[ 75  90 120 150 105]


In [43]:
print(Eachday_wage.sum())

540


In [44]:
np_nhrs[np_nhrs!=8]

array([ 5,  6, 10,  7])

In [45]:
np_nhrs[np_nhrs>=8]

array([ 8, 10])

In [49]:
np_nhrs[np_nhrs==8].size

1

In [51]:
np.logical_and(np_nhrs<8,np_nhrs>6)

array([False, False, False, False,  True])

In [52]:
np.logical_not(np_nhrs<8,np_nhrs>6)

array([False, False,  True,  True, False])

In [53]:
first_trial_Cyclist = [1,2,3,4]
second_trial_Cyclist = [10,20,30,40]
npfirst = np.array(first_trial_Cyclist)
npsecond = np.array(second_trial_Cyclist)

In [56]:
cyclist = np.array([[4,3,6,7,8],[2,3,3,4,5]])
cyclist

array([[4, 3, 6, 7, 8],
       [2, 3, 3, 4, 5]])

In [59]:
cyclist[0]

array([4, 3, 6, 7, 8])

In [60]:
cyclist[1]

array([2, 3, 3, 4, 5])

In [61]:
cyclist[0][1]

3

In [62]:
cyclist[1][2]

3

In [69]:
x = cyclist[:,1:]
x

array([[3, 6, 7, 8],
       [3, 3, 4, 5]])

In [68]:
for i in cyclist:
    print(i)


[4 3 6 7 8]
[2 3 3 4 5]


In [70]:
for i in x:
    print(i)


[3 6 7 8]
[3 3 4 5]


In [73]:
test_Score = np.array([35,33,37,40,32,39,38,35])
for i in test_Score :
    if i>=33:
        print(i)

35
33
37
40
39
38
35


In [74]:
test_Score[test_Score>33]

array([35, 37, 40, 39, 38, 35])

In [75]:
x = np.array([1,2,3,4,5])
y = x
y

array([1, 2, 3, 4, 5])

In [76]:
x is y

True

In [77]:
z = y.view()
z

array([1, 2, 3, 4, 5])

In [78]:
len(z)

5

In [79]:
z[4]=50
z

array([ 1,  2,  3,  4, 50])

In [80]:
y

array([ 1,  2,  3,  4, 50])

In [81]:
ysc = y.view()
print(ysc)
ydc = y.copy()
print(ydc)

[ 1  2  3  4 50]
[ 1  2  3  4 50]


In [82]:
ysc[4] =5
ysc

array([1, 2, 3, 4, 5])

In [83]:
y

array([1, 2, 3, 4, 5])

In [84]:
ydc[4]=35
ydc

array([ 1,  2,  3,  4, 35])

In [85]:
y

array([1, 2, 3, 4, 5])

In [86]:
np_sqrt = np.sqrt([4,9,16,25,36])
np_sqrt

array([2., 3., 4., 5., 6.])

In [88]:
from numpy import pi
np.cos(0)

1.0

In [89]:
np.sin(pi/2)

1.0

In [90]:
np.tan(pi)

-1.2246467991473532e-16

In [91]:
np.sin(pi)

1.2246467991473532e-16

In [92]:
np.floor([1.2,2.3,2.5,3.3])

array([1., 2., 2., 3.])

In [93]:
np.exp([0,1,2,3,4,5,6])

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 , 403.42879349])

In [95]:
x = np.array([1,2,3,4,5])
y = np.array([2,2,3,4,5])
x*y 

array([ 2,  4,  9, 16, 25])

In [96]:
c = 10
x*c

array([10, 20, 30, 40, 50])

In [97]:
x+y

array([ 3,  4,  6,  8, 10])

In [98]:
x-y

array([-1,  0,  0,  0,  0])

In [99]:
x/y

array([0.5, 1. , 1. , 1. , 1. ])

In [100]:
w1 = np.array([5,8,10,12,8,7])
w2 = np.array([10,9,14,12,10,5])

In [103]:
w = w1+w2

In [107]:
w11 = w1*15

In [108]:
w22 = w2*15

In [109]:
wt = w11 + w22

In [110]:
wt.sum()

1650

In [111]:
std1_scores = np.array([100,98,78,65,62])
std2_scores = np.array([100,99,79,65,68])

In [112]:
std_score = np.array([[100,98,78,65,62],[100,99,79,65,68]])
std_score.transpose()

array([[100, 100],
       [ 98,  99],
       [ 78,  79],
       [ 65,  65],
       [ 62,  68]])

In [116]:
A = np.array([[2,2],[3,3]])
print(A)
print(np.linalg.inv(A))

[[2 2]
 [3 3]]
[[-9.00719925e+15  6.00479950e+15]
 [ 9.00719925e+15 -6.00479950e+15]]


In [115]:
np.trace(A)

5

In [5]:
import numpy as np
w1 = np.array([[5,8,10,12,8,7]])
w2 = np.array([10,2])
w1*w2

ValueError: operands could not be broadcast together with shapes (1,6) (2,) 

In [9]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c.ravel()
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
c = np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [18]:
np.hsplit(c,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [24]:
import numpy as np
countries = np.array(['c1','c2','c3','c4','c5','c6','c7','c8','c9','c10'])
gdp = np.array([2000,3000,1500,2256,200,3556,755,888,9999,1234])
gdpmax = gdp.argmax()
print(gdpmax)
gdpmin = gdp.argmin()
print(gdpmin)
cmin = countries[gdpmin]
print(cmin)
cmax = countries[gdpmax]
print(cmax)



8
4
c5
c9


In [27]:
for country in countries:
    print(" Evauating Country: {}".format(country))

 Evauating Country: c1
 Evauating Country: c2
 Evauating Country: c3
 Evauating Country: c4
 Evauating Country: c5
 Evauating Country: c6
 Evauating Country: c7
 Evauating Country: c8
 Evauating Country: c9
 Evauating Country: c10


In [29]:
for i in range(len(countries)):
    country = countries[i]
    gdpc = gdp[i]
    print(" Country: {0} , GDP: {1}".format(country,gdpc))

 Country: c1 , GDP: 2000
 Country: c2 , GDP: 3000
 Country: c3 , GDP: 1500
 Country: c4 , GDP: 2256
 Country: c5 , GDP: 200
 Country: c6 , GDP: 3556
 Country: c7 , GDP: 755
 Country: c8 , GDP: 888
 Country: c9 , GDP: 9999
 Country: c10 , GDP: 1234


In [32]:
print(gdp.max())
print(gdp.min())
print(gdp.sum())
print(gdp.mean())
print(gdp.std())
print(gdp.sum())

9999
200
25388
2538.8
2672.656798019529
25388


In [33]:
import numpy as np
# Dataset for Summer Olympic London 2012
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_Bronze=np.array([19,22,32,29,7,17,14])

In [34]:
hg=np_olympic_Gold.argmax()
print(np_olympic_country[hg])

US


In [35]:
print(np_olympic_country [np_olympic_Gold >20])

['GBR' 'China' 'RUS' 'US']


In [37]:
for c in range(len(np_olympic_country)):
    print("Country:{0},Gold:{1},Silver:{2},Bronze:{3}".format(np_olympic_country[c],np_olympic_Gold[c],np_olympic_Silver[c],np_olympic_Bronze[c]))
    

Country:GBR,Gold:29,Silver:17,Bronze:19
Country:China,Gold:38,Silver:28,Bronze:22
Country:RUS,Gold:24,Silver:25,Bronze:32
Country:US,Gold:46,Silver:28,Bronze:29
Country:KOR,Gold:13,Silver:8,Bronze:7
Country:JPN,Gold:7,Silver:14,Bronze:17
Country:GER,Gold:11,Silver:11,Bronze:14


In [39]:
for c in range(len(np_olympic_country)):
    print("Country:{0},Gold:{1}".format(np_olympic_country[c],np_olympic_Gold[c]))

Country:GBR,Gold:29
Country:China,Gold:38
Country:RUS,Gold:24
Country:US,Gold:46
Country:KOR,Gold:13
Country:JPN,Gold:7
Country:GER,Gold:11


In [40]:

for c in range(len(np_olympic_country)):
     print("Country:{0},Medals:{1}".format(np_olympic_country[c],np_olympic_Gold[c] + np_olympic_Silver[c]+ np_olympic_Bronze[c]))

Country:GBR,Medals:65
Country:China,Medals:88
Country:RUS,Medals:81
Country:US,Medals:103
Country:KOR,Medals:28
Country:JPN,Medals:38
Country:GER,Medals:36
