In [10]:
# import required librares and data set
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [11]:
# view feature names of the dataset
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
# view target of the data set
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
# define features and target objects
X_feature = iris_dataset.data
Y_target = iris_dataset.target

In [14]:
#create object with new values for prediction
X_new = [[3,5,4,1],[5,3,4,2]]

In [17]:
# use the logistic regression estimator
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [18]:
# fit data into the logisics regression estimator 
logreg.fit(X_feature,Y_target)

C:\Users\thyagaraj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\thyagaraj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
# predict the outcome using regression estimator 
logreg.predict(X_new)

array([0, 2])

In [32]:
# import library for model persistance
import pickle as pkl

In [33]:
# use dumps method to persist the model
persist_model = pkl.dumps(logreg)
persist_model

b'\x80\x03csklearn.linear_model.logistic\nLogisticRegression\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00penaltyq\x03X\x02\x00\x00\x00l2q\x04X\x04\x00\x00\x00dualq\x05\x89X\x03\x00\x00\x00tolq\x06G?\x1a6\xe2\xeb\x1cC-X\x01\x00\x00\x00Cq\x07G?\xf0\x00\x00\x00\x00\x00\x00X\r\x00\x00\x00fit_interceptq\x08\x88X\x11\x00\x00\x00intercept_scalingq\tK\x01X\x0c\x00\x00\x00class_weightq\nNX\x0c\x00\x00\x00random_stateq\x0bNX\x06\x00\x00\x00solverq\x0cX\x04\x00\x00\x00warnq\rX\x08\x00\x00\x00max_iterq\x0eKdX\x0b\x00\x00\x00multi_classq\x0fh\rX\x07\x00\x00\x00verboseq\x10K\x00X\n\x00\x00\x00warm_startq\x11\x89X\x06\x00\x00\x00n_jobsq\x12NX\x08\x00\x00\x00classes_q\x13cnumpy.core.multiarray\n_reconstruct\nq\x14cnumpy\nndarray\nq\x15K\x00\x85q\x16C\x01bq\x17\x87q\x18Rq\x19(K\x01K\x03\x85q\x1acnumpy\ndtype\nq\x1bX\x02\x00\x00\x00i4q\x1cK\x00K\x01\x87q\x1dRq\x1e(K\x03X\x01\x00\x00\x00<q\x1fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq b\x89C\x0c\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00q!tq"bX\x05\x0

In [34]:
# use joblib.dump to persist the model to a file
from sklearn.externals import joblib
joblib.dump(logreg,'regresfilename.pkl')

['regresfilename.pkl']

In [35]:
# use joblib.load to persits the model to a file 
# craete new estimator from the saved model 
new_logreg_estimator = joblib.load('regresfilename.pkl')

In [36]:
# view the new estimator 
new_logreg_estimator

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [37]:
# validate and use new estimator to predict
new_logreg_estimator.predict(X_new)

array([0, 2])