In [1]:
from scipy.integrate import quad

In [2]:
def integrateFunction(x):
    return x

In [3]:
quad(integrateFunction,0,1)

(0.5, 5.551115123125783e-15)

In [4]:
def integrateFn(x,a,b):
    return x*a+b

In [5]:
a=3
b=2

In [6]:
quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [7]:
import scipy.integrate as integrate

In [8]:
def f(x,y):
    return x+y

integrate.dblquad(f,0,1,lambda x:0, lambda x:2)

(3.0, 4.436070580899685e-14)

In [15]:
y = lambda x:x*2 
print(y(2))

4


# Scipy Sub Pakage Optimization

In [16]:
import numpy as np
from scipy import optimize

In [17]:
def f(x):
    return x**2 + 5*np.sin(x)

In [21]:
minimaValue = optimize.minimize(f,x0=2,method ='bfgs',options = {'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 27
         Gradient evaluations: 9


In [22]:
minimaValueWithoutOpt = optimize.minimize(f,x0=2,method ='bfgs')

In [23]:
minimaValueWithoutOpt

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 27
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [24]:
import numpy as np
from scipy.optimize import root
def rootfunc(x):
    return x +3.5*np.cos(x)

In [25]:
rootValue = root(rootfunc,0.3)

In [26]:
rootValue

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

# Linear Algebra

In [27]:
import numpy as np
from scipy import linalg
matrix = np.array([[4,9],[3,5]])
matrix

array([[4, 9],
       [3, 5]])

In [34]:
type(matrix)

numpy.ndarray

In [33]:
linalg.inv(matrix)

array([[-0.71428571,  1.28571429],
       [ 0.42857143, -0.57142857]])

In [28]:
linalg.det(matrix)

-7.000000000000001

In [30]:
import numpy as np
from scipy import linalg
numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])
numArrValue = np.array([21,9,6])
linalg.solve(numArray,numArrValue)

array([ 4.95,  4.35, -1.95])

In [31]:
numSvdArr = np.array([[3,5,1],[9,5,7]])
numSvdArr.shape

(2, 3)

In [32]:
linalg.svd(numSvdArr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [35]:
import numpy as np
from scipy import linalg

In [38]:
A = np.array([[5,8],[7,9]])
eigenvalues,eigenvector = linalg.eig(A)
fev,sev = eigenvalues
print(fev,sev)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [42]:
print(eigenvector[:,0])

[-0.81220939  0.58336601]


In [43]:
print(eigenvector[:,1])

[-0.63447346 -0.77294465]


# Statistics 

In [44]:
from scipy.stats import norm

In [45]:
norm.rvs(loc=0,scale=1,size=10)

array([-0.83440754,  0.22604522, -0.72595631,  0.35606069, -0.24002519,
        0.31753615, -1.87853679, -0.1118331 , -0.35526533, -0.8565417 ])

In [46]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [47]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18

# Assignment1

#### Use SciPy to solve a linear algebra problem. There is a test with 30 questions worth 150 marks. 
#### The test has two types of questions: 
###### 1. True or false –carries 4 marks each 
##### 2. Multiple choice – carries 9 marks each 
#### Find the number of true or false and multiple choice questions.


In [2]:
import numpy as np
from scipy import linalg
tqvariable = np.array([[1,1],[4,9]])
tqvalue = np.array([30,150])
linalg.solve(tqvariable,tqvalue)


array([24.,  6.])

# Assignment2

#### Use SciPy to declare 20 random values for random values and perform the following: 
##### 1. CDF –Cumulative Distribution Function for 10 random variables. 
##### 2. PDF –Probability Density Function for 14 random variables.


In [5]:
from scipy.stats import norm
norm.rvs(loc=0,scale=1,size=20)

array([ 0.43220248, -0.62200358,  0.5413116 , -0.80755505,  0.00849012,
        0.36191213,  0.20625412, -0.15167064,  0.73608785, -1.64055898,
       -0.25703935,  0.28608273,  0.20972081,  1.31719171,  1.37199262,
       -0.80827698,  0.70242727,  1.35350438, -0.74022085,  0.05443966])

In [6]:
norm.cdf(10,loc=1,scale=3)

0.9986501019683699

In [10]:
norm.pdf(14,loc=1,scale=5)

0.002716593846737123